### PR TITLE
updated chromedriver version

### PR DESCRIPTION
**Pull request by dvoitekh**

### CODE REVIEW

**Comment by dvoitekh** [comment]
@rilian please review

**Comment by rilian** [comment]
please fix both compatible chromedriver and chrome versions

**Comment by dvoitekh** [comment]
@rilian done. plz check

**Comment by rilian** [comment]
@dvoitekh try `ruby:1.4`  image

**Comment by dvoitekh** [comment]
@rilian I automated choice of latest chromedriver. we can try building new image. `ruby:1.4` works fine with headless chrome

**Comment by rilian** [comment]
thanks, i will try to build this

**Comment by dvoitekh** [comment]
thank you

**Pull request merged**
